name: servant-aeson-specs
version: "0.5.1.1"
synopsis: generic tests for aeson serialization in servant
description: tests for aeson serialization in servant
category: Web
copyright: Plow Technologies
maintainer: soenkehahn@gmail.com, mchaver@gmail.com
author: Sönke Hahn, James M.C. Haver II
license: MIT
license-file: LICENSE
stability: alpha

github: plow-technologies/servant-aeson-specs

dependencies:
  - base < 5
  - aeson
  - bytestring
  - hspec
  - QuickCheck
  - servant >= 0.4 && < 0.10
  - directory
  - filepath
  - random
  - aeson-pretty
  - quickcheck-arbitrary-adt == 0.2.*
  - hspec-golden-aeson == 0.2.*

ghc-options:
  -Wall -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec-core
      - temporary
      - doctest
      - mockery
      - silently
      - quickcheck-instances
      - string-conversions
      - text
      - quickcheck-arbitrary-adt == 0.2.*
      - hspec-golden-aeson == 0.2.*

library:
  source-dirs:
    - src
